name:                hspotify
version:             0.1.0.0
github:              "m-ildefons/hspotify"
license:             BSD3
author:              "Moritz Röhrich"
maintainer:          "moritz.rohrich@suse.com"
copyright:           "2022 SUSE LLC."

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Haskell Spotify API Bindings.

dependencies:
  - aeson
  - async
  - base >= 4.7 && < 5
  - bytestring
  - data-default
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - optparse-applicative
  - prettyprinter
  - process
  - random
  - text
  - wai
  - warp

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path
  - -flate-dmd-anal

default-extensions:
  - DeriveAnyClass
  - DeriveGeneric
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TupleSections

library:
  source-dirs: src

executables:
  hspotify:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspotify

tests:
  hspotify-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspotify
